services:
  python-api:
    build:
      context: ./python-api
      dockerfile: Dockerfile
    container_name: tr-python-api-dev
    environment:
      - ENVIRONMENT=development
      - PORT=8000
    volumes:
      - ./python-api:/app
    command: ["uvicorn", "app:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
    ports:
      - "8000:8000"
    networks:
      - tr-network

  web-ui:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    container_name: tr-web-ui-dev
    environment:
      - NODE_ENV=development
      - NUXT_HOST=0.0.0.0
      - NUXT_PORT=3000
      - PYTHON_API_URL=http://python-api:8000
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.nuxt
      - /app/.output
    ports:
      - "3000:3000"
      - "24678:24678" # dev server HMR port
    depends_on:
      - python-api
    networks:
      - tr-network
    command: ["pnpm", "dev:local"]

networks:
  tr-network:
    driver: bridge
    name: trade-republic-network-dev
